language: node_js
node_js:
  - stable
install:
  - npm install
script:
  - npm start
  - npm test
env:
global:
  - $PORT=8081
  - process.env.PORT = 8080
after_success:
  - cat coverage/lcov.info | npx coveralls