language: node_js
node_js:
  - 15
  - 14
  - 13

cache: npm

install:
  - npm install
# script:
#   - npm run lint
#   - npm run build
#   - npm test
start:
  - npm start
after_success:
  - cat coverage/lcov.info | npx coveralls